import { Response } from 'express';
import prisma from '../prisma';
import { AuthenticatedRequest } from '../middleware/auth';
import { createAuditLog } from '../utils/audit';
import { generateInvoicePdf } from '../utils/pdfGenerator';
import { sendInvoiceEmail } from '../utils/mailer';

export async function createInvoice(req: AuthenticatedRequest, res: Response) {
  const { purchaseOrderId } = req.body;

  if (!purchaseOrderId) {
    return res.status(400).json({ error: 'Purchase Order ID is required' });
  }

  try {
    const po = await prisma.purchaseOrder.findUnique({
      where: { id: parseInt(purchaseOrderId) },
      include: {
        vendor: true,
        rfq: true,
      },
    });

    if (!po) {
      return res.status(404).json({ error: 'Purchase Order not found' });
    }

    // Check if invoice already exists for this PO
    const existing = await prisma.invoice.findFirst({
      where: { purchaseOrderId: po.id },
    });

    if (existing) {
      return res.status(400).json({ error: 'An invoice has already been generated for this Purchase Order' });
    }

    const currentYear = new Date().getFullYear();
    const invoiceCount = await prisma.invoice.count();
    const invoiceNumber = `INV-${currentYear}-${String(invoiceCount + 1).padStart(6, '0')}`;

    // GST Breakdown logic: assume 18% standard rate. Split equally into CGST & SGST (9% each)
    const totalTax = po.tax;
    const cgst = totalTax / 2;
    const sgst = totalTax / 2;

    const gstBreakdown = JSON.stringify({
      cgst: Math.round(cgst * 100) / 100,
      sgst: Math.round(sgst * 100) / 100,
      igst: 0.00,
    });

    const invoice = await prisma.invoice.create({
      data: {
        invoiceNumber,
        purchaseOrderId: po.id,
        totalAmount: po.totalAmount,
        taxAmount: totalTax,
        gstBreakdown,
        status: 'PENDING',
      },
    });

    // Update RFQ status to INVOICE_GENERATED
    await prisma.rfq.update({
      where: { id: po.rfqId },
      data: { status: 'INVOICE_GENERATED' },
    });

    // Notify Vendor (if generated by officer) or Officer (if generated by vendor)
    const notificationUser = po.createdById; // Notify the procurement officer
    await prisma.notification.create({
      data: {
        userId: notificationUser,
        message: `Invoice ${invoiceNumber} has been generated for Purchase Order ${po.poNumber}.`,
        type: 'INVOICE_GENERATED',
      },
    });

    await createAuditLog(
      req.user!.id,
      'INVOICE_GENERATION',
      `Generated Invoice ${invoiceNumber} for PO ${po.poNumber}`,
      req.ip
    );

    return res.status(201).json(invoice);
  } catch (error: any) {
    console.error('Invoice creation error:', error);
    return res.status(500).json({ error: error.message });
  }
}

export async function getAllInvoices(req: AuthenticatedRequest, res: Response) {
  const user = req.user;

  try {
    const whereClause: any = {};

    if (user?.role === 'VENDOR') {
      const vendor = await prisma.vendor.findUnique({
        where: { userId: user.id },
      });
      if (!vendor) return res.json([]);
      whereClause.purchaseOrder = {
        vendorId: vendor.id,
      };
    }

    const invoices = await prisma.invoice.findMany({
      where: whereClause,
      include: {
        purchaseOrder: {
          include: {
            rfq: true,
            vendor: true,
          },
        },
      },
      orderBy: { createdAt: 'desc' },
    });

    return res.json(invoices);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
}

export async function getInvoiceById(req: AuthenticatedRequest, res: Response) {
  const { id } = req.params;
  const user = req.user;

  try {
    const invoice = await prisma.invoice.findUnique({
      where: { id: parseInt(id) },
      include: {
        purchaseOrder: {
          include: {
            rfq: true,
            vendor: true,
            createdBy: { select: { name: true, email: true } },
          },
        },
        emails: {
          orderBy: { createdAt: 'desc' },
        },
      },
    });

    if (!invoice) {
      return res.status(404).json({ error: 'Invoice not found' });
    }

    // Auth check
    if (user?.role === 'VENDOR') {
      const vendor = await prisma.vendor.findUnique({ where: { userId: user.id } });
      if (invoice.purchaseOrder.vendorId !== vendor?.id) {
        return res.status(403).json({ error: 'Forbidden' });
      }
    }

    return res.json(invoice);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
}

export async function payInvoice(req: AuthenticatedRequest, res: Response) {
  const { id } = req.params;

  try {
    const invoice = await prisma.invoice.findUnique({
      where: { id: parseInt(id) },
      include: { purchaseOrder: { include: { vendor: true } } },
    });

    if (!invoice) {
      return res.status(404).json({ error: 'Invoice not found' });
    }

    const updated = await prisma.invoice.update({
      where: { id: invoice.id },
      data: { status: 'PAID' },
    });

    // Notify vendor
    if (invoice.purchaseOrder.vendor.userId) {
      await prisma.notification.create({
        data: {
          userId: invoice.purchaseOrder.vendor.userId,
          message: `Invoice ${invoice.invoiceNumber} has been marked as PAID. Funds have been disbursed.`,
          type: 'INVOICE_GENERATED',
        },
      });
    }

    await createAuditLog(
      req.user!.id,
      'INVOICE_UPDATE',
      `Paid Invoice ${invoice.invoiceNumber}. Total: ${invoice.totalAmount} INR`,
      req.ip
    );

    return res.json(updated);
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
}

export async function sendInvoice(req: AuthenticatedRequest, res: Response) {
  const { id } = req.params;

  try {
    const invoice = await prisma.invoice.findUnique({
      where: { id: parseInt(id) },
      include: {
        purchaseOrder: {
          include: {
            vendor: true,
            rfq: true,
            createdBy: { select: { name: true, email: true } },
          },
        },
      },
    });

    if (!invoice) {
      return res.status(404).json({ error: 'Invoice not found' });
    }

    // Default target email is custom recipient if provided, else PO author email or demo office address
    const recipientEmail = req.body.email || invoice.purchaseOrder.createdBy.email || 'officer@vendorbridge.com';

    // 1. Generate high-fidelity PDF
    const pdfBuffer = await generateInvoicePdf(invoice);

    // 2. Attach and send email
    const success = await sendInvoiceEmail({
      invoiceId: invoice.id,
      invoiceNumber: invoice.invoiceNumber,
      to: recipientEmail,
      pdfBuffer,
    });

    if (!success) {
      return res.status(500).json({ error: 'Failed to deliver email. Check system mail logs.' });
    }

    await createAuditLog(
      req.user!.id,
      'INVOICE_EMAIL_DISPATCH',
      `Emailed PDF of Invoice ${invoice.invoiceNumber} to ${recipientEmail}`,
      req.ip
    );

    return res.json({ message: `Invoice successfully emailed to ${recipientEmail}` });
  } catch (error: any) {
    console.error('Invoice send error:', error);
    return res.status(500).json({ error: error.message });
  }
}
